# Generated by Django 2.0.3 on 2018-03-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180322_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='event.Room'),
        ),
        migrations.AlterField(
            model_name='series',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
