# Generated by Django 2.0.3 on 2018-06-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20180614_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='keyholder',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='keyholder',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
